version: '2.0'

services:
  node1.onezone:
    image: $ONEZONE_IMAGE
    container_name: onezone-1
    hostname: node1
    domainname: onezone
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    extra_hosts:
      - "node1.onezone:127.0.1.1"
    # No port forwarding and better netowrk performance
    network_mode: host
    privileged: true
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        # configuration persistence
        - "${ONEZONE_CONFIGURATION_DIRECTORY}:/volumes/persistence"
        # Default configuration override
        - "${PWD}/oz-worker-overlay.config:/etc/oz_worker/overlay.config"
        - "${PWD}/oz-panel-overlay.config:/etc/oz_panel/overlay.config"
        # OpenId configuration
        #- "${AUTHORIZATION_CONFIGURATION_PATH}:/etc/oz_worker/auth.config"
        # Server SSL certificates
        - "/etc/letsencrypt/live/$ONEZONE_DOMAIN/privkey.pem:/etc/oz_panel/certs/web_key.pem"
        - "/etc/letsencrypt/live/$ONEZONE_DOMAIN/cert.pem:/etc/oz_panel/certs/web_cert.pem"
        - "/etc/letsencrypt/live/$ONEZONE_DOMAIN/chain.pem:/etc/oz_panel/certs/web_chain.pem"
        # Additional, trusted CA certificates (any filename is accepted)
        #- "${OZ_CACERTS_PATH}:/etc/oz_panel/cacerts/customCaBundle.pem"
    ulimits:
      # No core dumps created by rtransfer. TODO: Should be removed in the future.
      core: 0
      # For couchbase file limit to work on centos 7
      nproc: 65535
      nofile:
        soft: 63536
        hard: 63536
    environment:
      #ONEPANEL_DEBUG_MODE: "true" # prevents container exit on configuration error
      ONEPANEL_BATCH_MODE: "true"
      ONEPANEL_LOG_LEVEL: "error" # prints logs to stdout (possible values: none, debug, info, error), by default set to info
      ONEZONE_CONFIG: |
        cluster:
          domainName: "onezone"
          autoDeploy: true
          nodes:
            n1:
              hostname: "node1"
          managers:
            mainNode: "n1"
            nodes:
              - "n1"
          workers:
            nodes:
              - "n1"
          databases:
            # Per node Couchbase cache size in MB for all buckets
            serverQuota: 4096
            # Per bucket Couchbase cache size in MB across the cluster
            bucketQuota: 1024
            nodes:
              - "n1"
        onezone:
          name: "${ONEZONE_NAME}"
          domainName: "${ONEZONE_DOMAIN}"
          policies:
            subdomainDelegation: false
        onepanel:
          users:
            "admin":
              password: "password"
              userRole: "admin"
            "user":
              password: "password"
              userRole: "regular"
